services:
  - type: web
    name: task-management-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
    healthCheckPath: /
    autoDeploy: true 